import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google"; // Use valid Google Fonts
import "./globals.css";

// Import fonts with appropriate options
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap", // Optional for improved performance
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  display: "swap", // Optional for improved performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
